# Management 

## Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (2024, @tbl-man-ref-points). Sustainable total yields  were `r round(model_output$derived_quants[model_output$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model_output$derived_quants[model_output$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The 2025 spawning output relative to unfished equilibrium spawning output is above the `r Spp` relative biomass target of 40 percent (@fig-management-depletion). The fishing intensity, $1-SPR$, was below or just slightly above harvest rate limit ($SPR_{50\%}$) from the mid-1980s through the 1990s. Removals since 2000 have been below the point estimate of potential long-term yields calculated using an $\text{SPR}_{50\%}$ reference point (@tbl-man-timeseries and @fig-one-minus-spr). The equilibrium estimates of yield relative to biomass based on a steepness value fixed at `r round(model_output$parameters[model_output$parameters$Label == "SR_BH_steep","Value"], 2)` are provided in @fig-management-yield, where vertical dashed lines indicate the estimate of fraction unfished at the start of 2025 (current) and the estimated management targets calculated based on the relative target biomass (B target), the SPR target, and the maximum sustainable yield (MSY).

Reference points were based on the rockfish $\text{F}_{MSY\%}$ proxy ($\text{SPR}_{50\%}$), target relative biomass (40%), and estimated selectivity and catch for each fleet (@tbl-man-ref-points). The proxy MSY values of management quantities are by definition more conservative compared to the estimated MSY and MSY relative to 40% of unfished spawning output because of the assumed steepness value. Sustainable total yield, removals, using the proxy $\text{SPR}_{50\%}$ is `r round(model_output$derived_quants[model_output$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt. The spawning output equivalent to 40% of the unfished spawning output ($\text{SO}_{40\%}$) calculated using the SPR target ($\text{SPR}_{50\%}$) was `r round(model_output$derived_quants[model_output$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The 2025 spawning biomass relative to unfished equilibrium spawning biomass, based on the 2024 fishing year, is `r 100*(round(model_output$derived_quants[model_output$derived_quants$Label == 'Bratio_2025', 'Value'], 2))`%, above the management target of 40% of unfished spawning output. The relative biomass and the ratio of the estimated SPR to the management target ($\text{SPR}_{50\%}$) across all model years are shown in @fig-management-phase where cooler colors (purple) represent early years and warmer colors (yellow) represent recent years. The stock staus has not decreased below the target relative biomass, and fishing intensity (except for in 1995) has been below the target fishing intensity based on $\text{SPR}_{50\%}$.

## Management performance

In the last ten years total dead catches of `r Spp` have been below the annual catch limit. The last ten years total dead catches for `r Spp` against he overfishing limits (OFLs), the acceptable biological catches (ABCs), the annual catch limits (ACLs) are shown in @tbl-man-management. 

## Harvest Projections and Decision Tables

The `r Spp` assessment is being considered as a category 1 assessment with a $P^*$ = 0.45, $\sigma$ = 0.68 (estimated within the model, see @sec-uncertainty) and a time-varying buffer applied to set the ABC below the OFL. These multipliers are also combined with the rockfish MSY proxy of SPR\textsubscript{50} and the 40-10 harvest control rule to calculate OFLs and ACLs. Projections of the overfishing limit, acceptable biological catch, and annual catch limit, all based on a $P^*$ of 0.45 and a log-space standard deviation of the overfishing limit ($\sigma$) of 0.50 are included in @tbl-man-projections. Assumed catches for 2025 and 2026 for this projection were provided by the PFMC Groundfish Management Team, and catches from 2027 onward assume full attainment of the acceptable biological catch.

No decision table needed in draft assessments undergoing review.

## Evaluation of Scientific Uncertainty {#sec-uncertainty}

The model estimated uncertainty around the 2025 spawning output for is $\sigma$ = 0.6836465. The uncertainty around the OFL is$\sigma$ = 0.6713586. These $\sigma$ values underestimate the overall uncertainty as they do not incorporate the model structural uncertainty and do not account for any time-varying dynamics other than recruitment. The estimated uncertainty values are higher than the Category 1 default $\sigma$ = 0.5, so all projections will use the estimated $\sigma$. The alternative states of nature used to bracket uncertainty in the decision table assist with encapsulating model structure uncertainty.

## Research and Data Needs

There are many areas of research that could be improved to benefit the understanding and assessment of `r Spp`.  Below, we identify several of them that we consider particularly important.

*  Understanding the stock structure and biology of Rougheye and Blackspotted Rockfishes:  This assessment reports the status of `r Spp` as a pooled complex because it is extremely difficult to separate the catches of each species even in recent data, and attempting to do so would greatly increase the uncertainty in the predictions.  Because little is known about the respective biology and catch histories of the two species, it is unclear whether managing them as a complex may place one species at disproportionate risk of overfishing relative to the other.  Additional research that will provide insight into the distribution, life history, biological characteristics, and catch and discard profiles of the two species is recommended.  Such an endeavor would like require the efforts of at sea observers in all fleets, biologists aboard fishery-independent surveys, and port samplers along the entire West Coast requiring broad, inter-agency collaboration.

*  Understanding of coatwide stock structure, connectivity, and distribution:  This is a stock assessment for `r Spp` off of the west coast of the U.S. and does not consider data from British Columbia or Alaska.  Further investigating and comparing the data and predictions from British Columbia and Alaska to determine if there are similarities with the U.S. West Coast observations would help to define the connectivity between rougheye rockfish north of the U.S.-Canada border.

*	Natural mortality: Uncertainty in natural mortality translates into uncertain estimates of status and sustainable fishing levels for `r Spp`. `r spp` are one of the longest lived species of rockfish (with maximum age as old as 205 years reported in the literature). Assessment model was able to estimate female natural mortality, consistent with maximum age based meta-analytical prior, but with male natural mortality fixed at the median of the prior. The collection of additional age data and further research of the life-history of `r Spp` may improve our understanding of `r Spp` natural mortality.

* Historical landings and discards, including investigation of fisheries selectivity:  The substantial progress has been made in reconstructing historical landings of rockfishes on the U.S. West Coast, including those for `r Spp`. This assessment highlighted the importance of understanding of fishery selectivity assumptions associated with removals and how fishery selectivity changes throughout the years. Further understanding of this area would help reduce uncertainty in estimated scale of the stock.
